site_name: Kano Lab Docs

nav:
  - HOME:
      - 本サイトについて: index.md
  - Web:
      - web/index.md
      # - ログイン: https://docs.kano-lab.com/auth/login/
      # - 新規登録: https://docs.kano-lab.com/auth/register/
      - 教育システムデザイン:
          - web/lecture/index.md
          - 1. HTML の基礎と JavaScript: web/lecture/1.md
          - 2. グラフィクス: web/lecture/2.md
          - 3. アニメーション: web/lecture/3.md
          - 4. 物理シミュレーション: web/lecture/4.md
          - 5. インタフェース: web/lecture/5.md
          - 6. 3D グラフィクス: web/lecture/6.md
      - HTML 入門:
          - web/html-basics/index.md
          - 1. HTML とは: web/html-basics/1.md
          - 2. HTMLの基本構造: web/html-basics/2.md
          - 3. タグと要素の基本: web/html-basics/3.md
          - 4. テキストのフォーマット: web/html-basics/4.md
          - 5. リンクの作成: web/html-basics/5.md
          - 6. 画像の挿入: web/html-basics/6.md
          - 7. リストの作成: web/html-basics/7.md
          - 8. テーブルの作成: web/html-basics/8.md
          - 9. フォームの作成: web/html-basics/9.md
          - 10. HTML のセマンティクス: web/html-basics/10.md
          - 11. HTML のベストプラクティス: web/html-basics/11.md
          - 12. HTML の検証とデバッグ: web/html-basics/12.md
      - CSS 入門:
          - web/css-basics/index.md
          - 1. CSS の基本概念: web/css-basics/1.md
          - 2. セレクタとプロパティ: web/css-basics/2.md
          - 3. テキストのスタイリング: web/css-basics/3.md
          - 4. ボックスモデル: web/css-basics/4.md
          - 5. レイアウトの基本: web/css-basics/5.md
          - 6. 色と背景: web/css-basics/6.md
          - 7. フォントとタイポグラフィ: web/css-basics/7.md
          - 8. リストとテーブルのスタイリング: web/css-basics/8.md
          - 9. レスポンシブデザイン: web/css-basics/9.md
          - 10. アニメーションとトランジション: web/css-basics/10.md
          - 11. CSS フレームワークの紹介: web/css-basics/11.md
      - JavaScript 入門:
          - web/javascript-basics/index.md
          - 1. JavaScript の概要: web/javascript-basics/1.md
          - 2. 基本的な文法: web/javascript-basics/2.md
          - 3. 変数とデータ型: web/javascript-basics/3.md
          - 4. 演算子と式: web/javascript-basics/4.md
          - 5. 制御構文（条件分岐とループ）: web/javascript-basics/5.md
          - 6. 関数: web/javascript-basics/6.md
          - 7. 配列とオブジェクト: web/javascript-basics/7.md
          - 8. DOM 操作: web/javascript-basics/8.md
          - 9. イベントハンドリング: web/javascript-basics/9.md
          - 10. 非同期処理（コールバック、プロミス、async/await）: web/javascript-basics/10.md
          - 11. エラーハンドリング: web/javascript-basics/11.md
          - 12. モジュールとスコープ: web/javascript-basics/12.md
          - 13. デバッグとテスト: web/javascript-basics/13.md
          - 14. ブラウザ API の活用: web/javascript-basics/14.md
          - 15. JavaScript のベストプラクティス: web/javascript-basics/15.md
  - Java:
      - java/index.md
      - 環境構築: java/introduction/environment.md
      - Java 入門: java/introduction/grammar.md
      - GUI 開発:
          - java/gui/index.md
          - NetBeans 基礎: java/gui/netbeans.md
      - 画像処理:
          - java/ip/index.md
          - 画像データの入出力: java/ip/imageio.md
          - 画像処理の基礎: java/ip/basic.md
      - OpenCV:
          - java/opencv/index.md
          - インストール: java/opencv/introduction.md
          - 画像の表示: java/opencv/imread.md
          - 色空間: java/opencv/color.md
          - 画素値の操作: java/opencv/pixel.md
          - 二値化: java/opencv/threshold.md
          - フィルタ処理: java/opencv/filter.md
          - モルフォロジー演算: java/opencv/morphology.md
          - セグメンテーション: java/opencv/segmentation.md
          - 応用: java/opencv/advanced.md

  - Python:
      - python/index.md
      - 環境構築: python/environment.md
      - OpenCV: python/opencv/index.md
      - PyQt: python/pyqt/index.md
  - CT:
      - ct/index.md
      - True IR: ct/trueir.md
  - Git:
      - git/index.md
      - 導入: git/introduction.md
      - FTP接続: git/ftp.md

theme:
  # language: ja
  name: material
  custom_dir: overrides
  font:
    text: Noto Sans Japanese
  logo: img/chipmunk.png
  favicon: img/chipmunk.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra:
  generator: false
  analytics:
    provider: google
    property: G-32SPYS0ET7

extra_css:
  - css/extra.css

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - search

copyright: 　&copy; 2024 Kano Lab Docs
