site_name: Kano Lab Docs

nav:
  - HOME:
      - 本サイトについて: index.md
  - Java:
      - java/index.md
      - 環境構築: java/introduction/environment.md
      - Java 入門: java/introduction/grammar.md
      - GUI 開発:
          - java/gui/index.md
          - NetBeans 基礎: java/null.md
      - 画像処理:
          - java/ip/index.md
          - 画像データの入出力: java/ip/imageio.md
          - 画像処理の基礎: java/ip/basic.md
      - OpenCV:
          - java/opencv/index.md
          - インストール: java/opencv/introduction.md
          - 画像の表示: java/opencv/imread.md
          - 色空間: java/opencv/color.md
          - 画素値の操作: java/opencv/pixel.md
          - 二値化: java/opencv/threshold.md
          - フィルタ処理: java/opencv/filter.md
          - モルフォロジー演算: java/opencv/morphology.md
          - セグメンテーション: java/opencv/segmentation.md
          - 応用: java/opencv/advanced.md

  - Python:
      - python/index.md
      - 環境構築: python/environment.md
      - OpenCV: python/opencv/index.md
      - PyQt: python/pyqt/index.md
  - CT:
      - ct/index.md
      - True IR: ct/trueir.md
  - Git:
      - git/index.md
      - 導入: git/introduction.md
      - FTP接続: git/ftp.md

theme:
  # language: ja
  name: material
  font:
    text: Noto Sans Japanese
  logo: img/chipmunk.png
  favicon: img/chipmunk.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra:
  generator: false
  analytics:
    provider: google
    property: G-32SPYS0ET7

extra_css:
  - css/extra.css

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - search

copyright: 　&copy; 2023 Kano Lab Docs
